FROM {{ .python.from }}

# https://pypi.org/project/b2/
ENV BACKBLAZE_B2_VERSION {{ .version }}

RUN set -eux; \
	pip install --no-cache-dir "b2 == $BACKBLAZE_B2_VERSION"; \
	b2 version

CMD ["b2", "--help"]
