#!/bin/sh
set -e

# "modprobe" without modprobe
# https://twitter.com/lucabruno/status/902934379835662336

for module; do
# Docker often uses "modprobe -va foo bar baz"
	if [ "${module#-}" = "$module" ]; then
		ip link show "$module" || true
		lsmod | grep "$module" || true
	fi
done
