name: Verify Templating

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: verify-templating-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply Templates
        run: ./parallel.sh apply-templates.sh
      - name: Git Diff (informational)
        run: |
          git diff || :
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]
